### ISSUE TITLE
Ingress Template and Configuration

### ISSUE THREAD

**Issue by robertvy** [gitroomhq/postiz-helmchart#1]
### 📜 Description

I couldn't get Ingress working. I can also not see any ingress template but it is in values.yaml. Should this already be working.

### 👟 Reproduction steps

ingress:
  enabled: true
  className: 'alb'
  annotations:
    external-dns.alpha.kubernetes.io/hostname: xxxx
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: xxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  hosts:
    - host: xxxx
      paths:
        - path: /
          pathType: Prefix
  tls: []

### 👍 Expected behavior

ingress should be created

### 👎 Actual Behavior

no ingress created

### ☸️ Kubernetes Version

v1.29.7

### ⎈ Helm Version

v3.15.4

### 📊 Chart Version

1.0.1.

### ☁️ Cloud Provider

AWS

### 👀 Have you checked if this bug has been reported before?

- [X] I have searched existing issues and didn't find a similar bug report

### Are you willing to submit a PR?

Yes, I'm willing to submit a PR!

**Comment by vuisme** [comment]
We can insert ingress yaml to values for override it without template.

**Comment by jonathan-irvin** [comment]
So, I'll admit, this is a largely incomplete helm chart that is missing some of the main things. Together we can work on making it better. My IRL job has me pegged at the moment, but hopefully, I can bang something out soon.

**Comment by jamesread** [comment]
#2 adds support for ingress. Not sure why I closed this issue. oops.
