### ISSUE TITLE
🐛 Helm Chart Bug: Missing `ServiceAccount` template

### ISSUE THREAD

**Issue by zktaiga** [gitroomhq/postiz-helmchart#3]
### 📜 Description

There is no template for `ServiceAccount` creation, see:
```
Error creating: pods "postiz-postiz-app-768c7b798f-" is forbidden: error looking up service account default/postiz-postiz-app: serviceaccount "postiz-postiz-app" not found
```

The following is only used for templating the SA name in the deployment, but not to create it:
https://github.com/gitroomhq/postiz-helmchart/blob/005d53cce76075254e5ed6078e3cea05b239c728/charts/postiz/templates/_helpers.yaml#L53-L62

### 👟 Reproduction steps

Default values / service account creation enabled.

### 👍 Expected behavior

Successful deployment with default values.

### 👎 Actual Behavior

Pod can never be launched because there's no underlying SA created.

### ☸️ Kubernetes Version

v1.30.3

### ⎈ Helm Version

v3.14.3

### 📊 Chart Version

1.0.2

### ☁️ Cloud Provider

On-premises

### 👀 Have you checked if this bug has been reported before?

- [X] I have searched existing issues and didn't find a similar bug report

### Are you willing to submit a PR?

None

**Comment by jamesread** [comment]
Merged #4. Many thanks for the PR!

**Comment by MattyIceee** [comment]
Sorry to bug y'all but I think this was merged but never published

**Comment by jamesread** [comment]
Hey @MattyIceee , apologies, you're absolutely right! 

There's another PR open now, I'll see if we can get that closed and then I'll do a release. 

If I forget, could you raise a new issue - as seeing replies on closed issues is hard!
